unbind r
bind r source-file ~/.tmux.conf

unbind C-b
set-option -g prefix C-space
bind C-space send-prefix


set-option -g status-position top
set-option -sg escape-time 10
set-option -a terminal-features 'xterm-256color:RGB'

set -g mouse on
set -g default-terminal "tmux-256color"
set -g base-index 1
setw -g mode-keys vi

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resize with Ctrl + Arrow keys in 5-cell increments
bind-key -r -T prefix C-k resize-pane -U 5
bind-key -r -T prefix C-j resize-pane -D 5
bind-key -r -T prefix C-h resize-pane -L 5
bind-key -r -T prefix C-l resize-pane -R 5

unbind '"'
unbind %

bind-key "\\" split-window -h 
bind-key "|" split-window -fh 

bind-key "-" split-window -v 
bind-key "_" split-window -fv 


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"

set -g @tokyo-night-tmux_theme night   # night (default) | storm | moon | day
set -g @tokyo-night-tmux_transparent 0 # transparent background

set -g @tokyo-night-tmux_show_datetime 1             # local git status
set -g @tokyo-night-tmux_date_format MDY           # local git status
set -g @tokyo-night-tmux_time_format 12H           # local git status
set -g @tokyo-night-tmux_show_path 1            # current path
set -g @tokyo-night-tmux_path_format relative            # current path
set -g @tokyo-night-tmux_show_git 1             # local git status
set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
set -g @tokyo-night-tmux_show_netspeed 1        # network speed
set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
set -g @tokyo-night-tmux_show_music 1           # now playing

set -g @tokyo-night-tmux_show_right_widgets "git,wbg,netspeed,battery,datetime"

set -g @tokyo-night-tmux_show_hostname 0


# Configure Tmux
set -g status-position top
set -g status-justify "left"
set -g pane-border-lines simple
set -g pane-border-indicators off


# bootstrap tpm
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
